env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - import
  - prettier
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-function-return-type': error
