trailingComma: 'es5'
semi: true
singleQuote: true
bracketSpacing: true
htmlWhitespaceSensitivity: 'css'
printWidth: 100
overrides:
  - files:
      - '*.html'
      - '**/*.css'
      - '**/*.scss'
    options:
      singleQuote: false
